apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: k3s-whoami-homelab

servers: 1
agents: 1

registries:
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - "https://docker.mirrors.ustc.edu.cn"

ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer

  - port: 8443:443
    nodeFilters:
      - loadbalancer
